### ISSUE TITLE
PRACTICA_4_5_OPERACIONES_LECTURA_ESCRITURA

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-web-food#1]
[Operaciones de lectura y escritura practica 4-5.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-web-food/files/15224801/Operaciones.de.lectura.y.escritura.practica.4-5.pdf)

**Comment by Luz1727** [comment]
buen trabajo 19/20

**Comment by carlos0716c** [comment]
Portada = 25
Procedimiento = 25
Figuras, ilustraciones y fotografías = 25
Resultados y conclusiones = 25

Total = 100/100
CALIFICACIÓN =20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
